#!/usr/local/bin/php
<?php

define("LIVEZILLA_PATH","/var/www/html");

if (file_exists("/var/www/html/_definitions/definitions.inc.php")) {
    require "/var/www/html/_definitions/definitions.inc.php";
} else {
    echo "null";
    die;
}

if ( defined("VERSION") ) {
 echo constant("VERSION");
} else {
 echo "null";
}